### ISSUE TITLE
miss some key code

### ISSUE THREAD

**Issue by spence00** [DomenSoberl/deep-c#1]
1.exit  "ddpgc.h ",but there is no DDPGC. C source files.  it is case "int deepc_random_int(int min, int max);"  and "double 

2.deepc_random_double(double min, double max);" indefined.
"mlp_backpropagate(ddpg->critic, ddpg->criticErrors, LOSS_NONE);" in "ddpgc.h ",but  "LOSS_NONE" indefined.
<img width="531" alt="_20230806042946" src="https://github.com/DomenSoberl/deep-c/assets/141523885/2ab34075-f1f0-4ed5-9298-cc74de84cd22">

**Comment by DomenSoberl** [comment]
The DDPGC library depends on the MLPC library, which has to be linked when building DDPGC. The LOSS_NONE constant is defined in mlpc.h. I suggest compiling with the included Makefile, where these things are taken care of.
