### ISSUE TITLE
could you please write a evaluation class？

### ISSUE THREAD

**Issue by spence00** [DomenSoberl/deep-c#2]
if i have finish the train. but i want to load a new state, and want to get the reward base on the policy. how can i do? could you please write a evaluation class？thank you!

**Comment by DomenSoberl** [comment]
You don't get a reward from the trained policy, but from the environment that you provide yourself. From the trained policy you get an actions. You get an action based on a state by calling:

```c
double *ddpg_action(DDPG *ddpg, double *state);
``` 

You then execute the returned action in your environment, and the environment should then return a reward.
